AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloud Resume Challenge - Visitor Counter

Globals:
  Function:
    Timeout: 5
    Runtime: python3.11
    Handler: lambda_function.lambda_handler
    MemorySize: 128

Resources:
  SamVisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: SamVisitorCounterFunction
      Policies:
        - DynamoDBCrudPolicy:
            TableName: SamVisitorCounterTable
      Events:
        VisitorApi:
          Type: Api
          Properties:
            Path: /getSamVisitorCount
            Method: GET
      Environment:
        Variables:
          AWS_REGION: us-east-1

  SamVisitorCounterTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: SamVisitorCounterTable
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  ApiUrl:
    Description: "URL pública de la API para el contador de visitas"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getSamVisitorCount"
