AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Visitorssss counter application using API Gateway (HTTP), Lambda, and DynamoDB.

Globals:
  Function:
    Timeout: 3

Resources:
  SamHttpVisitorApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - GET
          - OPTIONS
        AllowHeaders:
          - Content-Type
        AllowOrigins:
          - https://jessicaherreraflores.com

  SamVisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: visitor-counter-table-sam
      Events:
        VisitorApi:
          Type: HttpApi
          Properties:
            Path: /getVisitorCount
            Method: GET
            ApiId: !Ref SamHttpVisitorApi

  SamVisitorCounterTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: visitor-counter-table-sam
      PrimaryKey:
        Name: id
        Type: String

Outputs:
  ApiUrl:
    Description: "HTTP API endpoint URL"
    Value: !Sub "https://${SamHttpVisitorApi}.execute-api.${AWS::Region}.amazonaws.com"
