name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt  # O dev-requirements.txt si prefieres

      - name: Deploy with SAM
        run: |
          sam build --template-file backend/template.yaml
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name visitor-counter-stack-sam \
            --capabilities CAPABILITY_IAM \
            --template-file backend/template.yaml
