name: Deploy backend with SAM

on:
  push:
    branches:
      - backend
    paths:
      - 'backend/**'

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r backend/requirements.txt
        pip install -r backend/dev-requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        source venv/bin/activate
        export PYTHONPATH=$PYTHONPATH:$(pwd)/backend
        pytest backend/tests/

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up SAM CLI
      uses: aws-actions/setup-sam@v2

    - name: Build with SAM
      run: |
        cd backend
        sam build

    - name: Deploy with SAM
      run: |
        cd backend
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM
