name: Test Lambda Function

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Configure AWS region
      run: echo "AWS_REGION=us-east-1" >> $GITHUB_ENV  # Define la región antes de ejecutar cualquier comando
      
    - name: Set fake AWS credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=fake" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=fake" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip uninstall -y moto  # Elimina cualquier versión instalada de moto
        pip install -r requirements.txt
        pip install "moto[all]==4.1.10"  # Instala una versión estable de moto

    - name: Run tests with pytest
      run: pytest test_lambda_function.py
